### ISSUE TITLE
Write tests for all crypto classes

### ISSUE THREAD

**Issue by matteomonti** [rainvg/drop#10]
Write tests for:
 - `box`
 - `channel`
 - `hash`
 - `keyexchanger`
 - `shorthash`
 - `signature`

**Comment by lromerio** [comment]
Done:

- `hash` 04a44c64cefa28711b99d0ea220152e1f7cbd173
- `shorthash` e3087b039cb3a86dfe917cdf52657afd3552626e
- `signature` 156d1894f21cc0d91c320b43dec6339921421d1b
- `keyexchanger` fc6f93252fab51c724c1f18e29db7f4e7d4e828d

**Comment by lromerio** [comment]
- `channel` ad44f92c09636ff9f0824bef722d2a2880ca3269 (missing `message_too_short` exception)

**Comment by lromerio** [comment]
- `box` ded11a29bcc9080b80e7cc8d2274d4e17ce030c4

In `signature` and `box` the exception `exception <encryption_failed, malformed_key>` is not tested yet.
